title: My Awesome Blog
description: A blog about web development, design, and technology
url: "https://yourdomain.com"
baseurl: "/Jekyll-blog-testing"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Navigation
navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
